#!/usr/bin/env python3
"""Dense text embeddings for IMR Qwen image descriptions.

Reads the free-text from qwen35_image_descriptions.jsonl (generated by
qwen35_describe_images.py), strips the chat-template/prompt echo and the
<think> block, then embeds each sentence with the Qwen3.5-4B text tower
(last-layer hidden state mean pooling, no generation).

Output: {output}/qwen35_image_text_embeddings.npz  (ids, embeddings, dim)

Replaces the coarse 27-dim categorical one-hot similarity with a dense
cosine text_sim in stage1_feature_knn_routes.load_qwen_image_text_sim.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np
import torch
from transformers import AutoModelForImageTextToText, AutoProcessor


ROOT = Path("/Data_8TB/lht/PseudoVideo-SAM3-X3-B7")
MODEL_PATH = Path("/Data_8TB/lht/models/Qwen3.5-4B")


def read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def clean_assistant(text: str) -> str:
    """Strip chat template / prompt echo / <think> block, keep the answer only."""
    marker = "assistant\n"
    idx = text.rfind(marker)
    out = text[idx + len(marker):] if idx >= 0 else text
    out = re.sub(r"<think>.*?</think>", "", out, flags=re.S)
    return out.strip()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--descriptions",
        type=Path,
        default=ROOT
        / "work/kvasir_1pct_anchors/qwen35_image_descriptions/qwen35_image_descriptions.jsonl",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT
        / "work/kvasir_1pct_anchors/qwen35_image_descriptions/qwen35_image_text_embeddings.npz",
    )
    parser.add_argument("--model", type=Path, default=MODEL_PATH)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--device", default="cuda")
    args = parser.parse_args()

    rows = read_jsonl(args.descriptions)
    texts = [clean_assistant(row["qwen_text"]) for row in rows]
    ids = [row["target_id"] for row in rows]
    print(f"rows={len(rows)} sample: {texts[0][:120]!r}", flush=True)

    processor = AutoProcessor.from_pretrained(str(args.model), trust_remote_code=True)
    model = AutoModelForImageTextToText.from_pretrained(
        str(args.model),
        torch_dtype="auto",
        device_map=args.device,
        trust_remote_code=True,
    ).eval()

    embs: list[np.ndarray] = []
    with torch.no_grad():
        for start in range(0, len(texts), args.batch_size):
            chunk = texts[start : start + args.batch_size]
            text = [processor.apply_chat_template(
                [{"role": "user", "content": t}],
                add_generation_prompt=False,
                enable_thinking=False,
            ) for t in chunk]
            inputs = processor(text=text, return_tensors="pt").to(args.device)
            out = model(**inputs, output_hidden_states=True)
            hidden = out.hidden_states[-1]  # (B, L, D)
            # mean-pool over non-padding tokens
            mask = inputs["attention_mask"].unsqueeze(-1).to(hidden.dtype)
            emb = (hidden * mask).sum(dim=1) / mask.sum(dim=1).clamp_min(1.0)
            emb = torch.nn.functional.normalize(emb, dim=-1)
            embs.append(emb.float().cpu().numpy())
            print(f"embedded {min(start + args.batch_size, len(texts))}/{len(texts)}", flush=True)

    arr = np.concatenate(embs, axis=0).astype(np.float32)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(args.output, ids=np.asarray(ids), embeddings=arr)
    print(json.dumps({"output": str(args.output), "rows": len(ids), "dim": int(arr.shape[1])}, indent=2))


if __name__ == "__main__":
    main()
